# Generated by Django 5.0.1 on 2024-02-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Restaurant_id',
        ),
    ]
