# Generated by Django 5.0.1 on 2024-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_restaurant_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
