# Generated by Django 5.0.1 on 2024-02-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_cart_customer_order_payment_product_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Name',
            new_name='name',
        ),
    ]
