# Generated by Django 5.0.1 on 2024-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_rename_product_food_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
