# Generated by Django 5.0.1 on 2024-03-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_food_item_image_restaurant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='product',
            new_name='food_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_item',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.cart')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.food_item')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
