# Generated by Django 5.0.1 on 2024-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_rename_quantity_cart_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
