# Generated by Django 5.0.1 on 2024-03-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_alter_cart_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant',
        ),
    ]
