# Generated by Django 5.0.1 on 2024-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_feedback_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='debit_card_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='upi',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
